version: '3'

networks:
  app-network:
    name: ${NETWORK}


services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "${EXPOSED_HTTP_PORT}:80"
    volumes:
      - ./code:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mysql-test
    networks:
      - app-network

  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    ports:
      - "${EXPOSED_MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  mysql-test:
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${TEST_DATABASE}
      MYSQL_USER: ${TEST_DATABASE}
      MYSQL_PASSWORD: ${TEST_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql-test
    env_file:
      - .env
    networks:
      - app-network

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./code:/var/www/html:delegated
    networks:
      - app-network

  redis:
    image: redis:bookworm
    restart: unless-stopped
    networks:
      - app-network

  composer:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./codes:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - app-network

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
      - mysql-test
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - app-network
