---
- name: Install Beanstalk
  apt: name=beanstalkd state=present

- name: Install Supervisor
  apt: name=supervisor state=present

- name: Copy Supervisor config
  copy: src=laravel-worker.conf dest=/etc/supervisor/conf.d/laravel-work.conf
  notify:
    - restart supervisor