---
- name: Install Postgres Server
  apt: name=postgresql state=present

- name: Install Postgres Client
  apt: name=postgresql-client state=present

- name: Install PIP
  apt: name=python3-pip state=present

- name: Install Postgres python bindings
  pip: name=psycopg2 state=present
