---
- name: Add ondrej/php
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install PHP and its modules
  apt: pkg={{ item }} state=latest
  with_items:
    - php7.4
    - php7.4-fpm
    - php7.4-pgsql
    - php7.4-curl
    - php7.4-xml
    - php7.4-mbstring
    - php7.4-memcached
    - php7.4-gd
    - php-imagick
  notify:
    - restart nginx

- include: composer.yml

- name: Set upload_max_filesize
  lineinfile: dest=/etc/php/7.4/fpm/php.ini regexp=^upload_max_filesize line='upload_max_filesize = 5M'
  notify:
    - restart nginx

- name: Make sure CLI logs to syslog
  lineinfile: dest=/etc/php/7.4/cli/php.ini regexp=^;?error_log line='error_log = syslog'

- name: Delete the cron php file
  file: path=/etc/cron.d/php state=absent

- name: Set session garbage collection on
  lineinfile: dest=/etc/php/7.4/fpm/php.ini regexp=^session.gc_probability line='session.gc_probability = 1'
  notify:
    - restart nginx
