---
- name: Add ondrej/php
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install PHP and its modules
  apt: pkg={{ item }} state=latest
  with_items:
    - php7.3
    - php7.3-fpm
    - php7.3-pgsql
    - php7.3-curl
    - php7.3-xml
    - php7.3-mbstring
    - php7.3-memcached
    - php7.3-gd
  notify:
    - restart nginx

- include: composer.yml

- name: Set upload_max_filesize
  lineinfile: dest=/etc/php/7.3/fpm/php.ini regexp=^upload_max_filesize line='upload_max_filesize = 5M'
  notify:
    - restart nginx

- name: Make sure CLI logs to syslog
  lineinfile: dest=/etc/php/7.2/cli/php.ini regexp=^;?error_log line='error_log = syslog'

- name: Delete the cron php file
  file: path=/etc/cron.d/php state=absent

- name: Set session garbage collection on
  lineinfile: dest=/etc/php/7.3/fpm/php.ini regexp=^session.gc_probability line='session.gc_probability = 1'
  notify:
    - restart nginx
