name: Code Checks

on:
  push:
    branches: [
      "main",
      "dev*"
    ]
  pull_request:
    branches: [
      "main",
      "dev*",
    ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3'
      - uses: actions/checkout@v4
      - name: Copy root .env
        working-directory: ./
        run: cp .env.example .env
      - name: Load Environment Config
        uses: falti/dotenv-action@v1.1.2
      - name: Copy code .env
        working-directory: ./code
        run: cp .env.example .env
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: ${{TEST_DATABASE}}
          mysql root password: ${{ MYSQL_ROOT_PASSWORD }}
          mysql user:  ${{TEST_DATABASE}}
          mysql password: ${{ TEST_DATABASE_PASSWORD }}
      - name: Install Dependencies
        working-directory: ./code
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        working-directory: ./code
        run: php artisan key:generate
      - name: Directory Permissions
        working-directory: ./code
        run: chmod -R 777 storage bootstrap/cache
      - name: Run tests
        working-directory: ./code
        env:
          TEST_DB_HOST: "localhost"
        run: php artisan test
