name: Code Checks

on:
  push:
    branches: [
      "main",
      "dev*"
    ]
  pull_request:
    branches: [
      "main",
      "dev*",
    ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3'
      - uses: actions/checkout@v4
      - name: Copy .env
        working-directory: ./code
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        working-directory: ./code
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        working-directory: ./code
        run: php artisan key:generate
      - name: Directory Permissions
        working-directory: ./code
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        working-directory: ./code
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        working-directory: ./code
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
